%YAML 1.1
---
Network:
  interface: enp4s0

Server:
  protocol: UDP
  port: 7777

Game:
  node:
    display_message: Yes
    references:
    actions:
      0x00:
        display_message: No
        title: Unknown 1.1
  host:
    display_message: Yes
    references:
    actions:
      0x00:
        display_message: No
        title: Unknown 2.1
