name: Python
# More information in:
# https://docs.github.com/en/actions/guides/building-and-testing-python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Perform:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

#      - name: CodeQL -> Initialize
#        uses: github/codeql-action/init@v1
#        with:
#          languages: python
#
#      - name: CodeQL -> Autobuild
#        uses: github/codeql-action/autobuild@v1
#
#      - name: CodeQL -> Perform analysis
#        uses: github/codeql-action/analyze@v1

      - name: Install dependencies
        run: |
          pwd
          cd ./src/
          pwd
          ls -lha
          python -m pip install --upgrade pip
          if [ -f .requirements.txt ]; then
            echo ""
            echo "=== Python: Install requirements from file ==="
            pip install -r .requirements.txt
          else
            echo ""
            echo "=== Python: Install default dependencies ==="
            pip install flake8 pylint pytest
          fi

      - name: PyLint -> Analyze the code
        run: |
          pwd
          cd ./src/
          pwd
          ls -lha
          pylint `ls -R|grep .py$|xargs`

      - name: Flake8 -> Lint
        run: |
          pwd
          cd ./src/
          pwd
          ls -lha
          flake8 .

      - name: PyTest -> Test
        run: |
          pwd
          cd ./src/
          pwd
          ls -lha
          echo ""
          echo "--------------------"
          pip list || true
          echo ""
          echo "--------------------"
          pip3 list || true
          echo ""
          echo "--------------------"
          python --version || true
          echo ""
          echo "--------------------"
          pytest --version || true
          echo ""
          echo "--------------------"
          pytest .
